/** คีย์การตั้งค่าที่โหลดครั้งเดียวใน layout (ลด request ซ้ำ) */
export const LAYOUT_PUBLIC_SETTING_KEYS = [
  "site_logo_url",
  "home_poster_enabled",
  "home_poster_image_url",
  "home_poster_link_url",
  "announcement_text",
  "announcement_enabled",
  "admin_contact_url",
  "home_youtube_url",
  "home_youtube_enabled",
  "home_youtube_title",
  "home_movies_enabled",
  "home_movie_poster_1",
  "home_movie_poster_2",
  "home_movie_poster_3",
  "home_movie_poster_4",
  "home_movie_poster_5",
  "home_featured_enabled",
  "home_shortcuts_enabled",
  "home_shortcut_image_1",
  "home_shortcut_link_1",
  "home_shortcut_image_2",
  "home_shortcut_link_2",
  "home_shortcut_image_3",
  "home_shortcut_link_3",
  "home_shortcut_image_4",
  "home_shortcut_link_4",
  "theme_color",
  "theme_color_nav",
  "theme_color_header_bg",
  "theme_color_bg_top",
  "theme_color_bg_bottom",
  "theme_color_text_accent",
  "theme_color_announcement",
  "site_title",
  "site_name",
  "site_description",
  "theme_color_text_main",
] as const;

export type LayoutPublicSettingKey = (typeof LAYOUT_PUBLIC_SETTING_KEYS)[number];

export type LayoutPublicSettings = Record<LayoutPublicSettingKey, string | null>;
